##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.9.0-B19] date: [Tue May 05 16:53:33 CEST 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = Nucleo-64-Light


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32f4xx_it.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
Core/Src/system_stm32f4xx.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usart.c

C_SOURCES += \
$(wildcard lvgl-release-v8.3/src/core/*.c) \
$(wildcard lvgl-release-v8.3/src/draw/*.c) \
$(wildcard lvgl-release-v8.3/src/draw/arm2d/*.c) \
$(wildcard lvgl-release-v8.3/src/draw/nxp/*.c) \
$(wildcard lvgl-release-v8.3/src/draw/nxp/pxp/*.c) \
$(wildcard lvgl-release-v8.3/src/draw/nxp/vglite/*.c) \
$(wildcard lvgl-release-v8.3/src/draw/renesas/*.c) \
$(wildcard lvgl-release-v8.3/src/draw/sdl/*.c) \
$(wildcard lvgl-release-v8.3/src/draw/stm32_dma2d/*.c) \
$(wildcard lvgl-release-v8.3/src/draw/sw/*.c) \
$(wildcard lvgl-release-v8.3/src/draw/swm341_dma2d/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/layouts/flex/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/layouts/grid/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/themes/basic/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/themes/default/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/themes/mono/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/animimg/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/calendar/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/chart/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/colorwheel/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/imgbtn/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/keyboard/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/led/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/list/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/menu/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/meter/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/msgbox/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/span/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/spinbox/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/spinner/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/tabview/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/tileview/*.c) \
$(wildcard lvgl-release-v8.3/src/extra/widgets/win/*.c) \
$(wildcard lvgl-release-v8.3/src/font/*.c) \
$(wildcard lvgl-release-v8.3/src/hal/*.c) \
$(wildcard lvgl-release-v8.3/src/misc/*.c) \
$(wildcard lvgl-release-v8.3/src/widgets/*.c) \
$(wildcard Drivers/ILI9341/*.c) \
$(wildcard UI/*.c) \
$(wildcard UI/screens/*.c) \
$(wildcard UI/widgets/*.c)

# ASM sources
AS_SOURCES =  \
startup_stm32f446xx.s \
context_switch.s

# ASMM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=soft

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F446xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/ILI9341 \
-Ilvgl-release-v8.3 \
-Ilvgl-release-v8.3/src \
-Ilvgl-release-v8.3/src/core \
-Ilvgl-release-v8.3/src/draw \
-Ilvgl-release-v8.3/src/draw/arm2d \
-Ilvgl-release-v8.3/src/draw/nxp \
-Ilvgl-release-v8.3/src/draw/nxp/pxp \
-Ilvgl-release-v8.3/src/draw/nxp/vglite \
-Ilvgl-release-v8.3/src/draw/renesas \
-Ilvgl-release-v8.3/src/draw/sdl \
-Ilvgl-release-v8.3/src/draw/stm32_dma2d \
-Ilvgl-release-v8.3/src/draw/sw \
-Ilvgl-release-v8.3/src/draw/swm341_dma2d \
-Ilvgl-release-v8.3/src/extra \
-Ilvgl-release-v8.3/src/extra/layouts/flex \
-Ilvgl-release-v8.3/src/extra/layouts/grid \
-Ilvgl-release-v8.3/src/extra/themes/basic \
-Ilvgl-release-v8.3/src/extra/themes/default \
-Ilvgl-release-v8.3/src/extra/themes/mono \
-Ilvgl-release-v8.3/src/font \
-Ilvgl-release-v8.3/src/hal \
-Ilvgl-release-v8.3/src/misc \
-Ilvgl-release-v8.3/src/widgets \
-IUI

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F446XX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(AS_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(AS_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
